# Generated by Django 4.0 on 2024-03-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_selectcandidatejob_candidate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='compnayName',
            new_name='companyName',
        ),
        migrations.AlterField(
            model_name='candidateapplications',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost'),
        ),
        migrations.AlterField(
            model_name='candidateapplications',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('selected', 'selected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='selectcandidatejob',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateapplications'),
        ),
    ]
