# Generated by Django 4.0 on 2024-04-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_rename_compnayname_jobpost_companyname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateapplications',
            name='resume',
        ),
    ]
